version: '3'
services:
  webapp:
    image: pathwaycommons/app-ui:master
    container_name: appui_webapp
    ports:
      - "9090:3000"
    environment:
      NODE_ENV: "production"
      PC_URL: "http://www.pathwaycommons.org/"
      FACTOID_URL: "http://factoid.baderlab.org/"